// reducer exports for easy import in redux store
export { default as filemanagerReducer  } from './filemanagerSlice'
export { default as settingsReducer  } from './settingsSlice'
export { default as configReducer  } from './configSlice'
export { default as productsClassificationReducer } from './shop/productsClassificationSlice'
export { default as postsClassificationReducer } from './contents/postsClassificationSlice'
export { default as newsClassificationReducer } from './news/newsClassificationSlice'
export { default as docClassificationReducer } from './doc/docClassificationSlice'
export { default as contentsReducer } from './contents/contentsSlice'
export { default as newsReducer } from './news/newsSlice'
export { default as docReducer } from './doc/docSlice'
export { default as productReducer } from './shop/productSlice'
export { default as keywordsCatcherReducer } from './keywordsCatcherSlice'
export { default as menuClassificationReducer } from './menus/menuClassificationSlice'
export { default as editorReducer } from './editorSlice'